config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'styleguide', to: 'pages#styleguide'
  get 'mission', to: 'pages#mission'
  resources :comparisons, only: %i[ show new create update destroy] do
    member do
      get 'worldmap'
    end
    # get 'create-entries', to: 'entries#create_entries'
    post 'create-entries', to: 'entries#create_entries'
    get 'remove-article-one', to: 'entries#remove_article_one'
    get 'remove-article-two', to: 'entries#remove_article_two'
    get 'add-article-one', to: 'entries#add_article_one'
    get 'add-article-two', to: 'entries#add_article_two'
  end

  resource :board, only: [:show]
  resources :entries, only: [:destroy]
end

app/views/shared/_articles.html.erb
<h1>Test Articles</h1>

<% @articles.each do |article| %>
  <ul>
    <li>
      <a href=<%= article["url"]%>>
        <p><%= article["author"] %>:
        <%= article["title"] %></p>
        <p><%= article["description"] %></p>
      </a>
    </li>
  </ul>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<p>All rights Reserved 2021</p>
</div>

app/views/shared/_form_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: <%= (controller_name == 'comparisons' && action_name == 'worldmap') ? "transparent" : "#191A1A" %>;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <div class="navbar-form">
    <%= simple_form_for @comparison do |f| %>
      <%= f.input :topic, placeholder: "Change topic" %>
      <%= f.input :end_date, as: :string, html5: true, input_html: {class: "datepicker"}, placeholder: "From*", label: false  %>
      <%= f.input :start_date, as: :string, html5: true, input_html: {class: "datepicker"}, placeholder: "To*", label: false %>
      <%= f.button :button, method: :post, class: "button-primary" do %>
        Search
      <% end %>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Board", board_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "My Board", board_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: <%= (controller_name == 'pages' && action_name == 'home') ? "transparent" : "#191A1A" %>;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Board", board_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "My Board", board_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_show_articles_api.html.erb
<% articles_one = locals[:articles_one]  %>
<% articles_two = locals[:articles_two]  %>
<% comparison = locals[:comparison]  %>

<div class="comparison-container">
<h1>News comparison</h1>

  <div class="articles-compare-container">
    <div class=articles-left>
   <h2 class="header" id="myHeader"> <%= articles_one.last["source"].capitalize unless (articles_one.empty? || articles_one.nil? ) %> </h2>
      <% @articles_one.each do |article| %>
        <% if article.nil? %>
          <script>alert("No more articles available from this publisher.")</script>
        <% else %>
        <div class="articles-card-container">
          <div class="articles-card-image">
            <% if article["image"].nil? %>
              <%= image_tag "no-image.png", alt: "image not found" %>
            <% else %>
              <img src=<%= article["image"]%> alt="article image">
            <% end %>
           </div>
          <div class="article-card-text">
            <div class="articles-card-date-cat">
              <p><%= article["category"].upcase %> </p>
              <%= article["published_at"].first(10) %>
              <%= link_to comparison_remove_article_one_path(@comparison, article), class: "maxi-remove-article-button" do %>
               <i class="far fa-window-close"></i>
              <% end %>
            </div>
            <div class="article-card-info">
              <h5 class="info-title"><%= article["title"] %> </h5>
              <p class="info-description"><%= article["description"] %> </p>
            </div>
            <div class="article-author-sentiment">
              <p class="author">Source: <%= article["source"] %> </p>
              <p class="sentiment">Sentiment: <%= article["sentiment_title_string"] %> </p>
            </div>
          <% end %>
         </div>
      <% end %>
      <%= link_to comparison_add_article_one_path(comparison), class: "maxi-add-article-button" do %>
        <span style="float: right; direction:rtl"><i class="fas fa-plus-circle"> <span>Add article</span></i></span>
      <% end %>

    </div>
      <div class="articles-right">
      <h2 class="header" id="myHeader"> <%= articles_two.last["source"].capitalize  unless articles_one.empty? %> </h2>
      <% @articles_two.each do |article| %>
         <% if article.nil? %>
          <script>alert("No more articles available from this publisher.")</script>
        <% else %>
        <div class="articles-card-container">
          <div class="article-card-text">
            <div class="articles-card-date-cat">
              <p><%= article["category"].upcase %> </p>
              <%= article["published_at"].first(10) %>
              <%= link_to comparison_remove_article_two_path(@comparison, article), class: "maxi-remove-article-button" do %>
               <i class="far fa-window-close"></i>
              <% end %>
            </div>
            <div class="article-card-info">
              <h5 class="info-title"><%= article["title"] %> </h5>
              <p class="info-description"><%= article["description"] %> </p>
            <div class="article-author-sentiment">
              <p class="author">Source: <%= article["source"] %> </p>
              <p class="sentiment">Sentiment: <%= article["sentiment_title_string"] %> </p>
            </div>
           </div>
            <div class="articles-card-image">
              <% if article["image"].nil? %>
              <%= image_tag "no-image.png", alt: "image not found" %>
            <% else %>
              <img src=<%= article["image"]%> alt="article image">
            <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <%= link_to comparison_add_article_two_path(comparison), class: "maxi-add-article-button" do %>
        <span><i class="fas fa-plus-circle"> <span>Add article</span></i></span>
      <% end %>
    </div>
  </div>

  <div class="save">
    <%= link_to 'Save', comparison_create_entries_path(comparison), method: :post, class: "button-white", id: "fixedbutton" %>
  </div>
</div>

app/views/shared/_show_articles_database.html.erb
<div class="comparison-container">
<% articles_one = locals[:articles_one]  %>
<% articles_two = locals[:articles_two]  %>
<% comparison = locals[:comparison]  %>
<% source = locals[:source]  %>
<% source_two = locals[:source_two]  %>

  <h1><%= comparison.topic.capitalize %></h1>

  <div class="articles-compare-container">
    <div class="articles-left" >
    <h2 class="header" id="myHeader"> <%= source[0].name %></h2>
      <% articles_one.each do |article| %>
        <div class="articles-card-container">
          <div class="articles-card-image">
            <img src=<%= article["image"]%> alt="article image">
          </div>
          <div>
            <div class="articles-card-date-cat">
              <p><%= article["category"].upcase %> </p>
              <%= article["published_at"].first(10) %>
            </div>
            <div class="article-card-info">
              <h5 class="info-title"><%= article["title"] %> </h5>
              <p class="info-description"><%= article["description"] %> </p>

              <p class="author">Source: <%= source[0]["name"] %> </p>
            </div>
          </div>
         </div>
      <% end %>

    </div>
      <div class="articles-right" >
      <h2><%= source_two[0]["name"] %></h2>
      <% articles_two.each do |article| %>
        <div class="articles-card-container">
          <div>
            <div class="articles-card-date-cat">
              <%= article["published_at"].first(10) %>
              <p><%= article["category"].upcase %> </p>
            </div>
            <div class="article-card-info">
              <h5 class="info-title"><%= article["title"] %> </h5>
              <p class="info-description"><%= article["description"] %> </p>
              <p class="author">Source: <%= source_two[0]["name"] %> </p>
            </div>
          </div>
          <div class="articles-card-image">
            <img src=<%= article["image"]%> alt="article image">
          </div>
         </div>
      <% end %>
    </div>
  </div>
</div>