config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'styleguide', to: 'pages#styleguide'
  get 'mission', to: 'pages#mission'
  resources :comparisons, only: %i[ show new create update destroy] do
    member do
      get 'worldmap'
    end
    # get 'create-entries', to: 'entries#create_entries'
    post 'create-entries', to: 'entries#create_entries'
    get 'remove-article-one', to: 'entries#remove_article_one'
    get 'remove-article-two', to: 'entries#remove_article_two'
    get 'add-article-one', to: 'entries#add_article_one'
    get 'add-article-two', to: 'entries#add_article_two'
  end

  resource :board, only: [:show]
  resources :entries, only: [:destroy]
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def show
    @comparisons_all = current_user.comparisons
    @comparisons = @comparisons_all.select do |comparison|
      comparison.articles_one.present?
    end
  end

end

app/views/boards/show.html.erb
<div class="row">

  <div class="col-sm-12 col-lg-5" id="board-card-container">
  <h1 id="headline-board-comparisons">Comparisons</h1>
  <% @comparisons.each do |comparison|%>
    <div class="board-card">
      <div class="container">
        <div class="row">
          <div class="board-card-left col-lg-7">
            <h3><%= comparison.topic.capitalize %></h3>
            <p class="board-source"><%= Source.find(comparison.publisher_one).name %></p>
            <p class="board-source"><%= Source.find(comparison.publisher_two).name%></p>

          </div>
          <div class="board-card-right col-lg-5">
            <%= link_to "Open Comparison", comparison_path(comparison)%>
          </div>
        </div>
        <div class="row">
          <div class="board-card-bottom col-lg-6 d-flex">
            <p><%= comparison.start_date%></p>
            <p><span>&nbspto </span><%= comparison.end_date%></p>
          </div>
          <div class="board-card-discussion-info col-lg-6 d-flex justify-content-between">
            <p>234</p>
            <p>comments</p>
            <p>See discussion</p>
          </div>
      </div>
      <div class="row">
        <div class="board-card-bottom-border col-lg-12">
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

  <div class="col-sm-12 col-lg-6" style="background-color: #191A1A; min-height: 100vh;">
  <h1 class="board-stats-text" style="margin: 50px 0px 0px 30px;">You have:&nbsp<%= @comparisons.count %>&nbspcomparisons</h1>
  </div>


</div>